### PR TITLE
Expose memoize functions with mappers and allow setting of equalityCheck to them.

### PR DESCRIPTION
**Pull request by LiborOl**
Hi, I have two requirements that covers this pull request.

1) I am creating npm package [reselect-map-change-memoize](https://github.com/LiborOl/reselect-map-change-memoize) similar to [reselect-change-memoize](https://github.com/kbrownlees/reselect-change-memoize) for reselect-map. I need to expose memoize functions of reselect-map to be able to detect, when the selector is recomputed.
2) I want to be able to change equalityCheck function.

Thanks for creating reselect-map and merging this pull request.
Libor.

### CODE REVIEW

**Comment by HeyImAlex** [comment]
I like it. It'll take about a week for me to get around to updating the documentation accordingly and to cut a new release. Thanks!

**Comment by HeyImAlex** [comment]
I was too lazy to write the documentation after all, but the new release has been published.

**Comment by HeyImAlex** [comment]
@LiborOl I just realized that somehow you didn't get contributing credit for this pull request. To be honest I'm not super experienced with git/github so it was likely a mistake on my end, but I just wanted to say that I'm sorry!

**Comment by LiborOl** [comment]
Oh, there are some 'cotributing credits' on github? :-) I didn't know that. No problem @HeyImAlex, but thank you for consern. I think, I am less experienced with github than you :-)

**Comment by LiborOl** [comment]
So I am contributor now :-) The problem was on my site. I commit under different email. I registered the second email in my account and it is ok now.

**Pull request merged**
